# Generated by Django 5.1.5 on 2025-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedDividendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('last_dividend', models.FloatField(blank=True, null=True)),
                ('dividend_date', models.CharField(blank=True, max_length=100, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=50, null=True)),
                ('dividend_yield_category', models.CharField(choices=[('4_to_7', '4~7%'), ('above_7', '7% 이상')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DividendTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
