# Generated by Django 5.1.4 on 2025-01-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('market', models.CharField(blank=True, max_length=100, null=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
