# Generated by Django 5.1.4 on 2025-01-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_dividendticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedDividendData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('last_dividend', models.FloatField(blank=True, null=True)),
                ('dividend_date', models.CharField(blank=True, max_length=100, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=50, null=True)),
                ('dividend_yield_category', models.CharField(choices=[('4_to_7', '4~7%'), ('above_7', '7% 이상')], max_length=20, null=True)),
            ],
        ),
    ]
