# Generated by Django 5.1.4 on 2025-01-21 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_collecteddividenddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collecteddividenddata',
            old_name='current_price',
            new_name='close',
        ),
    ]
